### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by mik3y**
Mechanical & mostly automatic changes to support Python 3.

Individual commits show command used to generate changes. This gets the the project building, running, and passing tests under python 3.

In a future change, I'd recommend we make the project python 3 only, as python 2 is EOL after 2019 & it would eliminate a needless opportunity for variation in environments. As part of that, we would review & remove all automatically-applied uses of `future` -- for example, many of the `old_div` sites here may be unnecessary.

### CODE REVIEW

**Comment by garthwebb** [comment]
Switch old_div to '/' please!  I think it's more clear this way and I don't think we need the compatibility.

**Comment by mik3y** [comment]
Can do! Stand by..

**Comment by mik3y** [comment]
@garthwebb OK, I re-ran disabling the `old_div` fix; baa148b is the new command and commit.

**Comment by mik3y** [comment]
Hmm, wait a sec, something didn't work. Stand by..

**Comment by mik3y** [comment]
OK - should be good to go, sorry for the swirl.

**Review by garthwebb — APPROVED** [review]

**Comment by garthwebb** [comment]
Looks good!

**Pull request merged**
